---
# File: install.yml - package installation tasks for Nomad

- name: OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nomad_os_packages }}"
  tags: installation

- name: Check Nomad package file already exist
  stat:
    path: "/tmp/nomad_{{ nomad_version }}.zip"
  become: false
  register: nomad_package

- name: Download Nomad {{ nomad_version }} archive
  get_url:
    url: "{{ nomad_zip_url }}"
    dest: "/tmp/nomad_{{ nomad_version }}.zip"
    checksum: "sha256:{{ nomad_checksum_file_url }}"
  become: false
  tags: installation
  when: not nomad_package.stat.exists

- name: Create Temporary Directory for Extraction
  tempfile:
    state: directory
    prefix: ansible-nomad.
  become: false
  register: install_temp
  tags: installation
  when: not nomad_package.stat.exists

- name: Unarchive Nomad
  unarchive:
    src: "/tmp/nomad_{{ nomad_version }}.zip"
    dest: "{{ install_temp.path }}/"
    creates: "{{ install_temp.path }}/nomad"
    remote_src: yes
  become: false
  tags: installation
  when: not nomad_package.stat.exists

- name: Install Nomad
  copy:
    src: "{{ install_temp.path }}/nomad"
    dest: "{{ nomad_bin_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: '0755'
    remote_src: yes
  tags: installation
  when: not nomad_package.stat.exists

- name: Cleanup
  file:
    path: "{{ install_temp.path }}"
    state: "absent"
  become: false
  tags: installation
  when: not nomad_package.stat.exists
